language: go
go: 1.6
sudo: required
services:
  - docker
  - mongodb
script:
  - make
install:
  - make deps
script:
  - make test
  - make coverprofile
  - make dockertest
after_success:
  - go get -v github.com/mattn/goveralls
  - goveralls -coverprofile=cover.profile -service=travis-ci
  - make dockertravis
