language: go
go: 1.6
services: mongodb
script:
  - make
install:
    - make deps
script:
    - make test
    - make coverprofile
after_success:
    - go get -v github.com/mattn/goveralls
    - goveralls -coverprofile=cover.profile -service=travis-ci

