language: go
go: 1.6
services: mongodb
install:
    - go get -v github.com/Masterminds/glide
    - cd $GOPATH/src/github.com/Masterminds/glide && git checkout e73500c735917e39a8b782e0632418ab70250341 && go install && cd -
    - glide install
script:
    - go test $(glide novendor) -v 
    - go test -v -covermode=count -coverprofile=profile.coverprofile
    - go test -v -covermode=count -coverprofile=db.coverprofile ./db
    - go test -v -covermode=count -coverprofile=mongo.coverprofile ./db/mongodb
    - go test -v -covermode=count -coverprofile=api.coverprofile ./api
after_success:
    - go get -v github.com/mattn/goveralls
    - go get github.com/modocache/gover
    - export PATH=$PATH:$HOME/gopath/bin
    - gover
    - goveralls -coverprofile=gover.coverprofile -service=travis-ci

